splash = false

wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures/wallpapers/wallpaper_4.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = ~/Pictures/wallpapers/wallpaper_3.png
    fit_mode = cover
}
